name: teacher_student_app
description: A Flutter application for teacher and student management at the University of Dhaka.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_animate: ^4.5.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dulogo.png
    - assets/profile.png
